import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " min-h-screen flex flex-col"}>
        <nav className="h-20 justify-between bg-green-400 flex items-center px-5">
          VERTICAL LAYOUT (NEXT)
          <div className="flex items-center gap-x-2">
            <Link href="/">Home</Link>
            <Link href="/dashboard">Dashboard</Link>
          </div>
        </nav>
        <main className="flex flex-col flex-grow relative">{children}</main>
        <footer className="h-20 bg-green-400">VERTICAL LAYOUT</footer>
      </body>
    </html>
  );
}
